version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8097:80"
        volumes:
            - ./dist_staging:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
