version: '2'

services:
    web_tesco_nutanix:
        image: nginx:latest
        ports:
            - "8099:80"
        volumes:
            - ./dist:/usr/share/nginx/html
            - ./nginx_proNutanix.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        restart: always

networks:
    code-network:
        driver: bridge
