version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8099:8099"
        volumes:
            - ./dist:/usr/share/nginx/html
            - ./nginx_pro.conf:/etc/nginx/conf.d/default.conf
            - ./sslkey/nginx.crt:/etc/nginx/ssl/nginx.cert
            - ./sslkey/nginx.key:/etc/nginx/ssl/nginx.key
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
